apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-ui-frontend
  labels:
    app: ai-ui-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-ui-frontend
  template:
    metadata:
      labels:
        app: ai-ui-frontend
    spec:
      containers:
      - name: ai-ui-frontend
        image: ghcr.io/umeshpoojariaws/ai-ui-backend:latest #ai-ui-frontend:local # Use local image for Kind deployment
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: ghcr-login-secret
